version: "3.8"

services:
  portfolio:
    build: .
    container_name: portfolio
    ports:
      - "3000:3000"
    restart: always
    networks:
      - project_devops

networks:
  project_devops:
    external: true
    name: project_devops
